swagger: "2.0"
info:
  title: "API Serverless"
  description: "Gateway para backend en Cloud Run"
  version: "1.0.0"
schemes:
  - "https"
produces:
  - "application/json"
paths:
  "/":
    get:
      summary: "Root Health Check"
      operationId: "rootGet"
      x-google-backend:
        address: ${backend_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        default:
          description: "Respuesta del backend"
  "/{path=**}":
    get:
      summary: "Proxy GET"
      operationId: "proxyGet"
      parameters:
        - name: path
          in: path
          required: true
          type: string
          description: "Ruta de destino"
      x-google-backend:
        address: ${backend_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        default:
          description: "Respuesta del backend"
    post:
      summary: "Proxy POST"
      operationId: "proxyPost"
      parameters:
        - name: path
          in: path
          required: true
          type: string
          description: "Ruta de destino"
      x-google-backend:
        address: ${backend_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        default:
          description: "Respuesta del backend"
    put:
      summary: "Proxy PUT"
      operationId: "proxyPut"
      parameters:
        - name: path
          in: path
          required: true
          type: string
          description: "Ruta de destino"
      x-google-backend:
        address: ${backend_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        default:
          description: "Respuesta del backend"
    delete:
      summary: "Proxy DELETE"
      operationId: "proxyDelete"
      parameters:
        - name: path
          in: path
          required: true
          type: string
          description: "Ruta de destino"
      x-google-backend:
        address: ${backend_url}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        default:
          description: "Respuesta del backend"